version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-posts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: posts_with_comments
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app-posts
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: dbpass
      DB_NAME: posts_with_comments
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
