version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-pwc
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: posts_with_comments
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s   
      timeout: 5s     
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
    container_name: app-pwc
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: dbpass
      DB_NAME: posts_with_comments
      MIGRATION_PATH: "file:///root/migrations/postgres"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
