// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string             `json:"id"`
	PostID    string             `json:"postId"`
	Text      string             `json:"text"`
	ParentID  *string            `json:"parentId,omitempty"`
	CreatedAt string             `json:"createdAt"`
	Children  *CommentConnection `json:"children"`
}

type CommentConnection struct {
	Edges    []*Comment `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Mutation struct {
}

type NewCommentInput struct {
	PostID   string  `json:"postId"`
	Text     string  `json:"text"`
	ParentID *string `json:"parentId,omitempty"`
}

type NewPostInput struct {
	Title            string `json:"title"`
	Content          string `json:"content"`
	CommentsDisabled bool   `json:"commentsDisabled"`
}

type PageInfo struct {
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type Post struct {
	ID               string             `json:"id"`
	Title            string             `json:"title"`
	Content          string             `json:"content"`
	CommentsDisabled bool               `json:"commentsDisabled"`
	Comments         *CommentConnection `json:"comments"`
}

type PostConnection struct {
	Edges    []*Post   `json:"edges"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type Query struct {
}

type Subscription struct {
}
